# Project Info:
site_name: API Connect Training 
site_description: API Connect Training
site_author: Ercan Canlıer

# Repository Info:
repo_name: ercancanlier/apiconnect-training
repo_url: https://github.com/ercancanlier/apiconnect-training

# Configuration
theme:
  name: material
  language: en
  extra:
  alternate:
    - name: Turkish
      link: /tr/ 
      lang: tr
  palette:
    - primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
font:
  text: Overpass
  code: Overpass Mono
icon:
  logo: material/receipt
  repo: fontawesome/brands/github

features:
  - navigation.instant
  - navigation.top
  - navigation.indexes
  - navigation.tracking
  - content.code.copy

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ercancanlier
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ercancanlier/

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - meta
  - attr_list

# Plugins
plugins:
  - search
  - git-authors
  - glightbox
  - tags:
      tags_file: tags.md

# Navigation
nav:
  - Introduction: index.md
  - Lab 1: lab1/lab1.md
  - Lab 2: lab2/lab2.md
  - Lab 3: lab3/lab3.md
  - Lab 4: lab4/lab4.md
  - Lab 5: lab5/lab5.md
  - Lab 6: lab6/lab6.md
  - Lab 7: lab7/lab7.md
  - Lab 8: lab8/lab8.md
  - Lab 9: lab9/lab9.md
  - Lab 10: lab10/lab10.md
  - Lab 11: lab11/lab11.md
  - Lab 12: lab12/lab12.md
  - Lab 13: lab13/lab13.md
  - Lab 14: lab14/lab14.md
  - Lab 15: lab15/lab15.md
  - Lab 16: lab16/lab16.md
  - Lab 17: lab17/lab17.md
  - Lab 18: lab18/lab18.md
  - Lab 19: lab19/lab19.md
  - Lab 20: lab20/lab20.md
  - Lab 21: lab21/lab21.md  

docs_dir: content/